### ISSUE TITLE
Add appropriate LICENSE File

### ISSUE THREAD

**Issue by kumarrishav** [OpenIoMeT/Weather-shimmer#6]
@snowmantw @kaichih  what license we should go for ?

**Comment by snowmantw** [comment]
I really don't have idea before we have a chance to discussion such non-tech issue. But maybe MIT first is a good decision we now can make.

**Comment by kumarrishav** [comment]
okay. So, we will go for MIT for now.

**Comment by kaichih** [comment]
I don't have a clear view on this either. Anyone we can consult with? Should we reopen this case to keep this topic in mind? Or we are pretty sure that MIT can fit our needs?

**Comment by kumarrishav** [comment]
As per greg, at initial stage MIT should be fine. Later if we need, we can modify or add new license to it.
